[package]
name = "typegraph"
version.workspace = true
edition.workspace = true

[dependencies]
regex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.128"
wasmtime.workspace = true
